FROM centos:7.5.1804

MAINTAINER Tashrif Billah <tbillah@bwh.harvard.edu>

    # set up working directory, redefine home directory, remain root user
WORKDIR /home/pnlbwh
ENV HOME=/home/pnlbwh
ENV USER="root"

COPY startup.sh /

    # install required libraries
RUN yum -y groupinstall 'development tools' && \
    yum -y install wget file bzip2 which vim git make libstdc++-static mesa-libGL bc tcsh libSM && \
    yum clean all && \
    #
    # install freesurfer
    echo "Downloading FreeSurfer" && \
    wget https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.1.0/freesurfer-linux-centos7_x86_64-7.1.0.tar.gz > /dev/null 2>&1 && \
    echo "Unzipping FreeSurfer tar ball" && \
    tar -xzf freesurfer-linux-centos7_x86_64-7.1.0.tar.gz && \
    rm -f freesurfer-linux-centos7_x86_64-7.1.0.tar.gz && \
    mv freesurfer freesurfer-7.1.0 && \
    #
    # install FSL
    echo "Downloading FSL installer" && \
    wget https://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py -O fslinstaller.py > /dev/null 2>&1 && \
    echo "Installing FSL" && \
    python fslinstaller.py -V 6.0.1 -d $HOME/fsl-6.0.1 -p > /dev/null 2>&1 && \
    # setup FSL environment
    export FSLDIR=$HOME/fsl-6.0.1 && \
    source $FSLDIR/etc/fslconf/fsl.sh && \
    $FSLDIR/fslpython/bin/conda clean -y --all && \
    rm -f fslinstaller.py && \
    #
    # install miniconda2 and whitematteranalysis package
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O Miniconda2-latest-Linux-x86_64.sh && \
    /bin/bash Miniconda2-latest-Linux-x86_64.sh -b -p miniconda2/ && \
    source miniconda2/bin/activate && \
    conda create -y -n wma python=2.7.13 && conda activate wma && \
    pip install git+https://github.com/SlicerDMRI/whitematteranalysis.git@fa98f26087d6cf26fcb2a1d50a7a18d73c361d93 && \
    #
    # initialize .bashrc
    cp /root/.bashrc $HOME/ && \
    echo "export PY2BIN=$HOME/miniconda2/envs/wma/bin" >> ~/.bashrc && \
    rm -rf .cache/pip/* && \
    rm -f Miniconda2-latest-Linux-x86_64.sh && \
    conda clean -y --all
    

    # install miniconda3
RUN wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O Miniconda3-latest-Linux-x86_64.sh && \
    /bin/bash Miniconda3-latest-Linux-x86_64.sh -b -p miniconda3/ && \
    git clone --recurse-submodules https://github.com/pnlbwh/pnlpipe.git && \
    #
    # create conda environment
    echo "source $HOME/miniconda3/bin/activate" >> ~/.bashrc && \
    source miniconda3/bin/activate && \
    conda env create -f pnlpipe/python_env/environment36.yml && \
    echo "conda activate pnlpipe3" >> ~/.bashrc && \
    conda activate pnlpipe3 && \
    #
    # back up incompatible libicuuc.*
    mv miniconda3/envs/pnlpipe3/lib/libicuuc.* /tmp/ && \
    cd pnlpipe && mkdir soft_dir && export PNLPIPE_SOFT=$HOME/pnlpipe/soft_dir && \
    ./pnlpipe std init && \
    ./pnlpipe std setup && \
    mv /tmp/libicuuc.* $HOME/miniconda3/envs/pnlpipe3/lib/ && \
    #
    # clean up sources
    conda clean -y --all && \
    rm -f $HOME/Miniconda3-latest-Linux-x86_64.sh && \
    cd soft_dir && rm -rf BRAINSTools BRAINSTools-build ANTs ANTs-build ukftractography UKFTractography-build dcm2niix && \
    rm -rf /tmp/* /var/tmp/* && \
    #
    # set up bashrc i.e shell
    echo "export PNLPIPE_SOFT=$HOME/pnlpipe/soft_dir" >> ~/.bashrc && \
    echo "alias ls=\"ls --color\"" >> ~/.bashrc && \
    echo "source \${PNLPIPE_SOFT}/BRAINSTools-bin-81a409d/env.sh" >> ~/.bashrc && \
    echo "source \${PNLPIPE_SOFT}/ANTs-bin-ca32228/env.sh" >> ~/.bashrc && \
    echo "source \${PNLPIPE_SOFT}/UKFTractography-2c144a3/env.sh" >> ~/.bashrc && \
    echo "source \${PNLPIPE_SOFT}/dcm2niix-c0a3731/env.sh" >> ~/.bashrc && \
    echo "source \${PNLPIPE_SOFT}/tract_querier-d4a88aa/env.sh" >> ~/.bashrc && \
    echo "export FSLDIR=$HOME/fsl-6.0.1" >> ~/.bashrc && \
    echo "source \$FSLDIR/etc/fslconf/fsl.sh" >> ~/.bashrc && \
    echo "export PATH=\$FSLDIR/bin:\$PATH" >> ~/.bashrc && \
    echo "export FREESURFER_HOME=$HOME/freesurfer-7.1.0" >> ~/.bashrc && \
    echo "source \${FREESURFER_HOME}/SetUpFreeSurfer.sh" >> ~/.bashrc && \
    echo "export PATH=$HOME/pnlpipe/pnlscripts:\$PATH" >> ~/.bashrc && \
    #
    # facilitate creation of ~/matlab/startup.m
    export FREESURFER_HOME=$HOME/freesurfer-7.1.0 && \
    source ${FREESURFER_HOME}/SetUpFreeSurfer.sh && \
    #
    # change permission of startup script 
    chmod +x /startup.sh
    

ENTRYPOINT ["/startup.sh"]

